version: "3"

tasks:
  flake8:
    desc: Lint the project with flake8
    cmds:
      - poetry run flake8 --benchmark --statistics tosaquestbot

  mypy:
    desc: Lint the project with mypy
    cmds:
      - poetry run mypy --config-file mypy.ini tosaquestbot

  isort:
    desc: Lint the project with isort
    cmds:
      - poetry run isort --check-only --diff tosaquestbot

  black:
    desc: Lint the project with black
    cmds:
      - poetry run black --check --diff tosaquestbot

  default:
    desc: Lint the project
    deps:
      - flake8
      - mypy
      - isort
      - black
