name: Lint

on:
  pull_request:
    branches: [ "master" ]
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Lint
        run: |
          task lint
